<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adresse' => '',
    'Avatar' => '',
    'Birthday' => '',
    'Booking Date' => '',
    'Booking Update' => '',
    'Cantidad' => '',
    'Capacity' => '',
    'Check In Date' => '',
    'Check Out Date' => '',
    'Created' => '',
    'Created At' => '',
    'Denominations' => '',
    'Description' => '',
    'Destination' => '',
    'Dimension (m2)' => '',
    'Email' => '',
    'Facilities' => '',
    'Faq Description' => '',
    'Faq Titel' => '',
    'Flag' => '',
    'Foto' => '',
    'High Price ' => '',
    'House' => '',
    'House Created At' => '',
    'House Name' => '',
    'House Rating' => '',
    'House Status' => '',
    'House Update At' => '',
    'Icon' => '',
    'Id Boock Status' => '',
    'Id Faq' => '',
    'Id House' => '',
    'Id Houseservice' => '',
    'Id Language' => '',
    'Id Owner' => '',
    'Id Region' => '',
    'Id Roomfacility' => '',
    'Id Services' => '',
    'Idroom' => '',
    'Imagens' => '',
    'Language' => '',
    'Language Code' => '',
    'Last Name' => '',
    'Low Price' => '',
    'Name' => '',
    'No' => '',
    'No.' => '',
    'Notes' => '',
    'Owner' => '',
    'Password' => '',
    'Phone' => '',
    'Photo' => '',
    'Price' => '',
    'Province' => '',
    'Province Code' => '',
    'Province Name' => '',
    'Region' => '',
    'Region Name' => '',
    'Roomfacilities' => '',
    'Services' => '',
    'Status' => '',
    'Status Description' => '',
    'Telef' => '',
    'Type' => '',
    'Type Desc' => '',
    'Type Room' => '',
    'Update' => '',
    'Updated At' => '',
    'User' => '',
    'idhouse' => '',
];
