<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adresse' => 'Dirección',
    'Avatar' => '',
    'Birthday' => 'Cumpleano',
    'Booking Date' => '',
    'Booking Update' => '',
    'Cantidad' => '',
    'Capacity' => 'Capacidad',
    'Check In Date' => 'Fecha de entrada',
    'Check Out Date' => 'Fecha de Salida',
    'Created' => 'Creado',
    'Created At' => '',
    'Denominations' => 'Denominación',
    'Description' => 'Descripción',
    'Dimension (m2)' => '',
    'Email' => '',
    'Facilities' => '',
    'Faq Description' => '',
    'Faq Titel' => '',
    'Flag' => '',
    'Foto' => '',
    'High Price ' => '',
    'House' => '',
    'House Created At' => '',
    'House Name' => '',
    'House Rating' => '',
    'House Status' => '',
    'House Update At' => '',
    'Icon' => '',
    'Id Boock Status' => '',
    'Id Faq' => '',
    'Id House' => '',
    'Id Houseservice' => '',
    'Id Language' => '',
    'Id Owner' => '',
    'Id Region' => '',
    'Id Roomfacility' => '',
    'Id Services' => '',
    'Idroom' => '',
    'Imagens' => 'Imagenes',
    'Language' => 'Lenguaje',
    'Language Code' => 'Lenguaje',
    'Last Name' => 'Apellido',
    'Low Price' => 'Precio bajo',
    'Name' => 'Nombre',
    'No' => '',
    'No.' => '',
    'Notes' => 'Notas',
    'Owner' => 'Dueno',
    'Password' => 'Contrasena',
    'Phone' => 'Móvil',
    'Photo' => 'Foto',
    'Price' => 'Precio',
    'Province' => 'Provincia',
    'Province Code' => 'Código de la Provincia',
    'Province Name' => 'Nombre de la Provincia',
    'Region' => 'Región',
    'Region Name' => 'Nombre de la Región',
    'Roomfacilities' => 'Facilidades',
    'Services' => 'Servicios',
    'Status' => 'Estado',
    'Status Description' => 'Descripción del Estado',
    'Telef' => 'Telf',
    'Type' => 'Tipo',
    'Type Desc' => '',
    'Type Room' => 'Tipo de Habitación',
    'Update' => 'Actualizar',
    'Updated At' => 'Actualizado',
    'User' => 'Usuario',
    'idhouse' => '',
    'About' => 'Quienes somos',
    'Contact' => 'Contactar',
    'Home' => 'Inicio',
    'Login' => 'Login',
    'Register' => 'Registrarse',
    'Welcome' => 'Bienvenido',
    'Destination' => 'Destinos',
];
